// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: days.queries.sql

package day_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDay = `-- name: CreateDay :exec
INSERT INTO days (date, day_of_week, month_id)
VALUES ($1, $2, $3)
`

type CreateDayParams struct {
	Date      pgtype.Date
	DayOfWeek int32
	MonthID   pgtype.UUID
}

func (q *Queries) CreateDay(ctx context.Context, arg CreateDayParams) error {
	_, err := q.db.Exec(ctx, createDay, arg.Date, arg.DayOfWeek, arg.MonthID)
	return err
}

const createRangeOfDays = `-- name: CreateRangeOfDays :exec
INSERT INTO days (date, day_of_week, month_id)
SELECT 
    gs::date as date,
    EXTRACT(DOW FROM gs)::int as day_of_week,
    $1 as month_id
FROM generate_series($2::date, $3::date, '1 day') AS gs
`

type CreateRangeOfDaysParams struct {
	MonthID   pgtype.UUID
	DateStart pgtype.Date
	DateEnd   pgtype.Date
}

func (q *Queries) CreateRangeOfDays(ctx context.Context, arg CreateRangeOfDaysParams) error {
	_, err := q.db.Exec(ctx, createRangeOfDays, arg.MonthID, arg.DateStart, arg.DateEnd)
	return err
}

const updateDayById = `-- name: UpdateDayById :exec
UPDATE days
SET date = $2,
    day_of_week = $3,
    month_id = $4
WHERE id = $1
`

type UpdateDayByIdParams struct {
	ID        pgtype.UUID
	Date      pgtype.Date
	DayOfWeek int32
	MonthID   pgtype.UUID
}

func (q *Queries) UpdateDayById(ctx context.Context, arg UpdateDayByIdParams) error {
	_, err := q.db.Exec(ctx, updateDayById,
		arg.ID,
		arg.Date,
		arg.DayOfWeek,
		arg.MonthID,
	)
	return err
}
