// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package day_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Day struct {
	ID        pgtype.UUID
	Date      pgtype.Date
	DayOfWeek int32
	MonthID   pgtype.UUID
}
