// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package day_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Day struct {
	ID        pgtype.UUID `json:"id"`
	Date      pgtype.Date `json:"date"`
	DayOfWeek int32       `json:"day_of_week"`
	MonthID   pgtype.UUID `json:"month_id"`
}
