// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package month_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Month struct {
	ID        pgtype.UUID
	Year      int32
	Month     int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
