// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: months.sql

package month_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonth = `-- name: CreateMonth :exec
INSERT INTO months (month, year)
VALUES ($1, $2)
`

type CreateMonthParams struct {
	Month int32
	Year  int32
}

func (q *Queries) CreateMonth(ctx context.Context, arg CreateMonthParams) error {
	_, err := q.db.Exec(ctx, createMonth, arg.Month, arg.Year)
	return err
}

const deleleMonth = `-- name: DeleleMonth :exec
DELETE FROM months
WHERE id = $1
`

func (q *Queries) DeleleMonth(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleleMonth, id)
	return err
}
