// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: months.queries.sql

package month_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonth = `-- name: CreateMonth :one
INSERT INTO months (month, year)
VALUES ($1, $2)
RETURNING id
`

type CreateMonthParams struct {
	Month int32
	Year  int32
}

func (q *Queries) CreateMonth(ctx context.Context, arg CreateMonthParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMonth, arg.Month, arg.Year)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleleMonth = `-- name: DeleleMonth :exec
DELETE FROM months
WHERE id = $1
`

func (q *Queries) DeleleMonth(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleleMonth, id)
	return err
}
