// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package task_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Day struct {
	ID        pgtype.UUID
	Date      pgtype.Date
	DayOfWeek int32
	MonthID   pgtype.UUID
}

type Month struct {
	ID        pgtype.UUID
	Year      int32
	Month     int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Task struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Status      interface{}
	TimeStart   pgtype.Time
	TimeEnd     pgtype.Time
	DayID       pgtype.UUID
}
