// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Username    string
	Password    string
	Email       string
	PhoneNumber string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
