// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package task_category_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Month struct {
	ID        pgtype.UUID        `json:"id"`
	Year      int32              `json:"year"`
	Month     int32              `json:"month"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TaskCategory struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	MonthID     pgtype.UUID `json:"month_id"`
}
